### PR TITLE
Add basic procedure support and minor generator first

### PR DESCRIPTION
**Pull request by KlemenDEV**
Changes:

-  Added basic procedure support (and some example implementation)
- Fixed bug with yaml being set to json type which caused formatter errors in mcreator.log

### CODE REVIEW

**Review by BoogieMonster1O1 — CHANGES_REQUESTED** [review]
Any reason fully qualified class names are being used in most of the places?

**Comment by KlemenDEV** [comment]
> Any reason fully qualified class names are being used in most of the places?

Current 2020.4 snapshot does not properly (auto)import org.bukkit :D I will fix this in the final 2020.4 release. Thus option is to specify imports manually or use FQDN.

**Comment by KlemenDEV** [comment]
Looking again Player might not need FQDN but would need to test.

**Comment by cs2s** [comment]
can you help me with the + thing 

I load the plugin from the downloads, 
restart the mcreator and when i open 
it doesn't show the spigot plugin thing

**Comment by Goldorion** [comment]
Last snapshot!

**Pull request merged**
